### ISSUE TITLE
Script stopped working after Feedly redesign in early April 2019

### ISSUE THREAD

**Issue by fajfka** [bittremieux/feedly-unread#1]
Hello, Wout.

Would it be possible to verify the functionality of the script after a redesign of Feedly, which took about 3 weeks back, and since that time your script no longer displays unread items?
I tried Dan's script from https://github.com/dmahr1/feedly-enhancer-chrome/blob/master/feedly-unread-favicon.js - it shows the numbers of unread, but I have other problems there..

Thanks, Petr F.

**Comment by bittremieux** [comment]
Should be fixed with the latest version. Let me know if you have any more problems.
